### ISSUE TITLE
Ajouter colonne nb actions et pourcentage de hold dans holdings

### ISSUE THREAD

**Issue by marmix** [HEG-Arc/marmix#6]

**Comment by cgaspoz** [comment]
@antoinerosselet ready for inclusion in the dashboard...

**Comment by antoinerosselet** [comment]
done

**Comment by cgaspoz** [comment]
C'est un double done ;-)
Merci
Le 18 mars 2015 10:23, "antoinerosselet" notifications@github.com a écrit
:
